# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          - task: QualysWASConnector@1
            inputs:
              webApplication: '268983027-testApp'
              scanType: 'VULNERABILITY'
              optionProfile: 'Other'
              profileName: '1415216'
              failBySeverity4: true
              sev4: '1'
              failBySeverity5: true
              sev5: '1'
              failwithAnyQIDs: true
              qidlist: '150001'
              dataCheckFrequency: '5'
              waitTimeforScanResult: '60*24'
              WasService: 'US2'